// Realistic fake client for demos and testing. Nothing here is a real company.
export const SAMPLE_ANSWERS = {
  company_name: 'Harborline Health Software',
  respondent: 'Dana Ruiz, CEO and co-founder',
  one_liner: 'Scheduling and patient-messaging software for multi-location dental groups, priced per location.',
  stage: 'Growth ($1M–$10M)',
  revenue_range: '$5M–$10M',
  team_size: 48,
  business_model: ['SaaS subscription', 'Services / consulting'],
  why_now: 'Growth stalled around $6M ARR for three quarters. The board wants a credible 2027 plan at the March meeting, and the leadership team disagrees about whether the problem is product (no two-way texting) or sales (we lost our VP Sales in June).',
  success_90: 'Board approves a focused 2027 plan; we have picked one segment to lead with; pipeline coverage back above 3x; a decision on whether to raise a bridge.',
  goal_rank: ['Grow revenue', 'Fix go-to-market', 'Improve product-market fit', 'Raise capital', 'Improve profitability', 'Build the team / org', 'Prepare for an exit'],
  plan_confidence: 2,
  current_strategy: 'Win mid-size dental groups (5–40 locations) with a direct inside-sales team, then expand into billing and reminders add-ons. In 2025 we also started selling to single-location practices through a low-touch starter tier.',
  revenue_target: 8200000,
  revenue_forecast: 6700000,
  growth_rate: 9,
  results_detail: 'Better: retention held (GRR 91%) and the reminders add-on is in 38% of accounts. Worse: new bookings missed plan by about 30%. Two enterprise deals (DSOs with 120+ locations) slipped twice, outbound produced almost nothing, and the starter tier pulled reps into small deals.',
  ideal_customer: 'Dental groups with 10–30 locations, bought by the COO or Director of Operations after a bad quarter of front-desk turnover and missed appointments.',
  customer_count: 214,
  top_customer_share: 11,
  grr: 91,
  nrr: 98,
  competitors: 'Weave, NexHealth, Dentrix built-in scheduling, spreadsheets',
  win_loss: 'We win on multi-location reporting and implementation support. We lose on two-way texting (Weave) and on price against NexHealth for smaller groups.',
  market_position: 3,
  channels: ['Inbound / content', 'Outbound sales', 'Referrals', 'Events'],
  sales_motion: 'Inside sales',
  acv: 21000,
  sales_cycle: 74,
  win_rate: 27,
  cac: 26000,
  pricing: '$350 per location per month on annual contracts; unchanged since 2023. Average discount is 18% and reps discount at the end of every quarter.',
  rate_sales: 2,
  rate_marketing: 2,
  rate_pricing: 2,
  product_summary: 'Scheduling, reminders and multi-location reporting. Roadmap: two-way texting (Q1), online booking widget (Q2), insurance verification (2027).',
  rate_pmf: 3,
  product_gap: 'No two-way texting. Prospects ask for it in about half of demos.',
  leadership: 'Dana Ruiz CEO (6 yrs); Sam Patel CTO (6 yrs); VP Sales open since June; Priya Nair VP Customer Success (3 yrs); Kim Lee finance (contract, 2 days/week).',
  open_roles: 'VP Sales, product marketing manager',
  rate_org: 2,
  cash: 4100000,
  burn: 310000,
  runway: 18,
  gross_margin: 74,
  funding: 'Seed $3M (2021), Series A $9M (2023). Considering a $3M bridge in Q2 if bookings do not recover.',
  metrics_tracked: 'ARR, new bookings, churn, cash. We do not track pipeline coverage or CAC consistently.',
  problem_1: 'New bookings are about 30% below plan and pipeline is thin',
  problem_1_sev: 5,
  problem_2: 'Leadership disagrees on whether to fix product or sales first',
  problem_2_sev: 4,
  problem_3: 'Starter tier pulls reps into small, low-value deals',
  problem_3_sev: 3,
  tried: 'Hired an outbound agency for six months ($90K): 4 meetings, no deals. Launched the starter tier in 2025; it now takes 35% of rep time for 8% of new ARR.',
  why_failed: 'The agency never understood dental operations. The starter tier was priced to win, not to make money, and we never set rules for which deals reps should take.',
  budget: '$50K–$150K',
  timing: 'Board meeting March 12. If we raise a bridge, we need to start conversations by mid-April.',
  politics: 'Sam (CTO) believes the answer is two-way texting and is wary of pricing changes. Priya wants to slow new sales until onboarding is fixed.',
  non_negotiables: 'No layoffs in customer success. We will not exit the single-location market entirely this year.',
  decision_maker: 'Dana Ruiz, with board approval for budget over $250K',
  stakeholders: 'Sam Patel (CTO): owns roadmap. Priya Nair (VP CS): owns retention. Ellen Wu (board chair): pushing for profitability by 2027.',
  kickoff_attendees: 'Dana, Sam, Priya, Kim',
  board_involvement: 'Will review the plan',
  file_pitch: [], file_financials: [], file_board: [], file_other: [],
};

// A reply in the format the "Copy prompt" asks any AI to return, written for the sample client.
export const SAMPLE_AI_REPLY = `\`\`\`json
{
 "deck": {
  "title": "Harborline: fix pipeline before product bets",
  "subtitle": "What we heard and where we propose to focus first",
  "health": "Yellow",
  "slides": [
   {"layout": "summary", "section": "Executive summary", "title": "Harborline's growth problem is pipeline and focus, not retention",
    "items": [
     {"label": "Plan gap", "value": "-18%", "answer": "Revenue will land $1.5M below the $8.2M target", "tone": "bad"},
     {"label": "Runway", "value": "13 mo", "answer": "Cash ÷ burn says 13 months, not the 18 stated", "tone": "warn"},
     {"label": "Retention", "value": "91%", "answer": "Customers stay; the base is a strength to build on", "tone": "good"},
     {"label": "Top problem", "value": "5/5", "answer": "Bookings 30% below plan with thin pipeline", "tone": "bad"},
     {"label": "Unit economics", "value": "~20 mo", "answer": "CAC payback is long because deals are discounted", "tone": "warn"},
     {"label": "Proposal", "value": "3 areas", "answer": "Segment focus, pricing discipline, a rebuilt sales engine", "tone": "neutral"}
    ],
    "takeaway": "The base is healthy; the growth engine and the plan need resetting.",
    "notes": "Open with the headline: retention is not the issue. The gap to plan comes from new bookings. Flag that the runway the client stated (18 months) does not match cash divided by burn (about 13 months) and ask Kim to confirm the burn figure. Ask Dana whether the board has seen the revised forecast."},
   {"layout": "bignumbers", "section": "Current state", "title": "Revenue will miss plan by 18% and runway is shorter than stated",
    "items": [
     {"icon": "down", "value": "$6.7M", "label": "Revenue now expected this year", "sub": "vs. $8.2M target", "tone": "bad"},
     {"icon": "clock", "value": "13 mo", "label": "Runway at current burn", "sub": "$4.1M cash · $310K/mo burn", "tone": "warn"},
     {"icon": "people", "value": "91%", "label": "Gross revenue retention", "sub": "Net retention 98%", "tone": "good"}
    ],
    "takeaway": "Any plan has to pay back inside about a year of cash.",
    "notes": "The stated runway is 18 months; cash of $4.1M at $310K a month burn gives about 13. Either burn has fallen recently or the runway figure includes the bridge. Confirm at kickoff. Growth was 9% last year against a plan that implied about 30%."},
   {"layout": "hero", "section": "Self-assessment", "title": "Leadership rates sales, marketing and pricing as its weakest areas",
    "chart": "ratings",
    "stats": [
     {"value": "2/5", "label": "Sales, marketing, pricing and alignment", "tone": "bad"},
     {"value": "3/5", "label": "Product-market fit and market position", "tone": "warn"}
    ],
    "takeaway": "The team's own ratings point at go-to-market, not product.",
    "notes": "Four areas score 2 of 5. Note that the CTO argues the fix is product (two-way texting) while product-market fit is rated higher than every go-to-market area. Use this chart to open the product-versus-sales debate with data rather than opinions."},
   {"layout": "ranked", "section": "Key problems", "title": "Thin pipeline is the most severe problem; the other two make it worse",
    "items": [
     {"title": "New bookings 30% below plan, thin pipeline", "detail": "Outbound agency: 4 meetings in 6 months; no pipeline coverage metric", "score": "5", "tone": "bad"},
     {"title": "Leaders split on product vs. sales", "detail": "CTO backs texting; VP CS wants to slow sales; VP Sales seat open", "score": "4", "tone": "bad"},
     {"title": "Starter tier pulls reps into small deals", "detail": "35% of rep time for 8% of new ARR", "score": "3", "tone": "warn"}
    ],
    "takeaway": "Problem 2 blocks the fix for problem 1: alignment comes first.",
    "notes": "Ask the team whether they agree with this order. The starter tier is a symptom of having no rules for which deals to pursue. The leadership split is the reason nothing has been decided since June."},
   {"layout": "cards", "section": "Opportunities", "title": "Three opportunities can close most of the gap without new product",
    "cards": [
     {"title": "Stop discounting by default", "body": "Average discount is 18% and price is unchanged since 2023. Halving discounting is worth roughly $0.4M a year.", "tone": "good"},
     {"title": "Focus reps on 10–30 location groups", "body": "Best customers are clearly defined; win rate is 27% when reps get qualified at-bats.", "tone": "good"},
     {"title": "Expand the base", "body": "GRR 91% but NRR only 98%: reminders is in 38% of accounts, billing add-on in few.", "tone": "good"}
    ],
    "takeaway": "Pricing discipline and focus are faster than the texting roadmap.",
    "notes": "The discount figure is the client's own. The $0.4M estimate assumes about $5M of new and renewing contract value repriced over a year at 9 points less discount; treat as directional. Expansion: ask Priya for add-on penetration by account size."},
   {"layout": "decisions", "section": "Focus areas", "title": "We propose three focus areas for the first 90 days",
    "items": [
     {"title": "Pick the lead segment", "body": "Agree the 10–30 location focus and deal rules by week 6; owner Dana with BKCG.", "why": "Starter tier: 35% of rep time, 8% of ARR"},
     {"title": "Reset pricing and discount rules", "body": "Test a packaging and discount policy on new deals from week 8; owner Kim with BKCG.", "why": "18% average discount, price unchanged since 2023"},
     {"title": "Rebuild the sales engine", "body": "Define pipeline coverage, hire the VP Sales, replace the agency with a focused outbound play by week 12.", "why": "Bookings 30% below plan"}
    ],
    "takeaway": "One segment, one price policy, one pipeline metric.",
    "notes": "Two-way texting stays on the roadmap; this plan does not depend on it. That framing should help with Sam. The VP Sales hire is the long pole; start the search in week 1."},
   {"layout": "compare", "section": "Today vs. proposed", "title": "The proposal narrows the focus and adds discipline",
    "fromLabel": "Today", "toLabel": "Proposed",
    "rows": [
     {"icon": "target", "from": "Sell to every practice size", "to": "Lead with 10–30 location groups", "why": "Best-fit customers convert and stay"},
     {"icon": "cash", "from": "18% average discount, no rules", "to": "Discount approval above 10%", "why": "Price unchanged since 2023"},
     {"icon": "chart", "from": "ARR and bookings only", "to": "Weekly pipeline coverage target 3x", "why": "Gap was visible too late"},
     {"icon": "people", "from": "VP Sales seat open since June", "to": "Hire by week 12", "why": "No owner for the number"}
    ],
    "takeaway": "Each change is reversible and measurable within a quarter.",
    "notes": "Walk through each row and ask who owns it on the client side."},
   {"layout": "cards", "section": "Risks", "title": "Cash and alignment are the risks that could derail the plan",
    "cards": [
     {"title": "Runway may be 13 months, not 18", "body": "If correct, the bridge decision moves up to April.", "tone": "bad"},
     {"title": "CTO and VP CS not bought in", "body": "Both favor different fixes; involve them in the diagnosis, not the readout.", "tone": "warn"},
     {"title": "Board timing", "body": "March 12 board meeting leaves 10 weeks to land a plan.", "tone": "warn"},
     {"title": "Pricing change spooks customers", "body": "Apply new rules to new deals first; renewals later.", "tone": "warn"}
    ],
    "takeaway": "Confirm burn and get Sam and Priya into the diagnostic early.",
    "notes": "The runway discrepancy is the most urgent item to confirm at kickoff."},
   {"layout": "timeline", "section": "Next steps", "title": "Twelve weeks to an approved plan, with a decision at week 8",
    "items": [], "takeaway": "Readout in week 5 and board-ready plan before March 12.",
    "notes": "Timeline fills from the project plan. Key dates: diagnostic readout week 5, strategy workshop week 8, approval week 12."}
  ]
 },
 "plan": {"rows": [
  {"phase": "Discover", "workstream": "Engagement", "task": "Kickoff and goals alignment", "owner": "BKCG, Dana Ruiz", "start": 1, "weeks": 1, "deliverable": "Agreed goals and scope", "milestone": true},
  {"phase": "Discover", "workstream": "Engagement", "task": "Leadership interviews (Dana, Sam, Priya, Kim)", "owner": "BKCG", "start": 1, "weeks": 2, "deliverable": "Interview synthesis", "milestone": false},
  {"phase": "Discover", "workstream": "Finance", "task": "Confirm burn, runway and bridge timing", "owner": "Kim Lee", "start": 1, "weeks": 2, "deliverable": "Cash model", "milestone": false},
  {"phase": "Discover", "workstream": "Sales", "task": "Pipeline and lost-deal data pull", "owner": "Dana Ruiz", "start": 1, "weeks": 2, "deliverable": "Pipeline data pack", "milestone": false},
  {"phase": "Discover", "workstream": "Customers", "task": "Customer and lost-deal interviews (10)", "owner": "BKCG", "start": 2, "weeks": 3, "deliverable": "Customer insights", "milestone": false},
  {"phase": "Diagnose", "workstream": "Segment", "task": "Segment profitability and win-rate analysis", "owner": "BKCG", "start": 3, "weeks": 2, "deliverable": "Segment scorecard", "milestone": false},
  {"phase": "Diagnose", "workstream": "Pricing", "task": "Discount and price-realization analysis", "owner": "BKCG, Kim Lee", "start": 3, "weeks": 2, "deliverable": "Pricing diagnostic", "milestone": false},
  {"phase": "Diagnose", "workstream": "Sales", "task": "Sales funnel and capacity diagnostic", "owner": "BKCG", "start": 3, "weeks": 2, "deliverable": "Funnel diagnostic", "milestone": false},
  {"phase": "Diagnose", "workstream": "Engagement", "task": "Diagnostic readout to leadership", "owner": "BKCG", "start": 5, "weeks": 1, "deliverable": "Readout deck", "milestone": true},
  {"phase": "Design", "workstream": "Segment", "task": "Lead segment and deal rules", "owner": "Dana Ruiz, BKCG", "start": 6, "weeks": 2, "deliverable": "Segment strategy", "milestone": false},
  {"phase": "Design", "workstream": "Pricing", "task": "Packaging and discount policy", "owner": "Kim Lee, BKCG", "start": 6, "weeks": 2, "deliverable": "Pricing policy", "milestone": false},
  {"phase": "Design", "workstream": "Sales", "task": "Pipeline coverage model and outbound play", "owner": "BKCG", "start": 6, "weeks": 3, "deliverable": "Sales playbook v1", "milestone": false},
  {"phase": "Hiring", "workstream": "Sales", "task": "VP Sales search and scorecard", "owner": "Dana Ruiz", "start": 2, "weeks": 10, "deliverable": "VP Sales hired", "milestone": false},
  {"phase": "Design", "workstream": "Engagement", "task": "Leadership strategy workshop", "owner": "BKCG, leadership team", "start": 8, "weeks": 1, "deliverable": "Chosen direction", "milestone": true},
  {"phase": "Plan & mobilize", "workstream": "Execution", "task": "90-day action plan with owners", "owner": "BKCG, leadership team", "start": 9, "weeks": 2, "deliverable": "90-day plan", "milestone": false},
  {"phase": "Plan & mobilize", "workstream": "Execution", "task": "KPI scorecard and weekly cadence", "owner": "Kim Lee", "start": 9, "weeks": 2, "deliverable": "Weekly scorecard", "milestone": false},
  {"phase": "Plan & mobilize", "workstream": "Finance", "task": "Board pack and bridge decision", "owner": "Dana Ruiz, Kim Lee", "start": 10, "weeks": 2, "deliverable": "Board-ready plan", "milestone": false},
  {"phase": "Plan & mobilize", "workstream": "Engagement", "task": "Final recommendation and approval", "owner": "Dana Ruiz", "start": 12, "weeks": 1, "deliverable": "Approved plan", "milestone": true}
 ]}
}
\`\`\``;

// ---------------------------------------------------------------- Financial system implementation sample
export const FINSYS_SAMPLE_ANSWERS = {
  company_name: 'Keystone Industrial Supply',
  respondent: 'Maria Chen, CFO',
  one_liner: 'We distribute industrial MRO supplies and private-label safety products to manufacturers in the Mid-Atlantic from five warehouses.',
  fs_industry: 'Distribution / wholesale',
  fs_revenue: '$100M–$250M',
  team_size: 420,
  fs_ownership: 'Private equity backed',
  fs_locations: 7,
  fs_triggers: ['Outgrown the current system', 'Acquisition or new entities', 'Current system losing vendor support', 'Leadership lacks timely reporting', 'Too much manual work / spreadsheets'],
  why_now: 'We acquired Delmarva Fastener (2025) and Lehigh Safety (2026) and now consolidate four companies in Excel. Close takes 15 business days and our lender wants covenant reporting by the 20th. Sage 100 support at the acquired companies ends June 2027, and our PE sponsor has two more acquisitions in the pipeline.',
  success_90: 'Leadership agrees on how acquired companies will run, requirements are signed off, a system and implementation partner are selected, and the board has approved a go-live date and budget.',
  fs_success_golive: 'Close in 6 days, consolidated reporting without Excel, gross margin by customer and product line after freight and rebates, and the ability to fold in the next acquisition within 90 days without adding finance headcount.',
  fs_priority_rank: ['Multi-entity consolidation', 'Faster month-end close', 'Better management reporting', 'Scale for growth and M&A', 'Controls and audit readiness', 'Budgeting and forecasting', 'Automation of AP / AR', 'Lower total cost of systems'],
  current_strategy: 'Grow from $165M to $300M by 2029, roughly half through acquiring regional distributors and half organically, while growing the private-label safety line from 6% to 15% of revenue and launching an e-commerce channel for small manufacturers.',
  fs_growth_moves: ['Acquisitions', 'New legal entities', 'New business lines or revenue models', 'E-commerce channel', 'Sale of the company / recapitalization'],
  fs_cant_do: 'We cannot see margin by customer or product line after freight and rebates, so reps discount blindly. Pricing for the private-label line is set on gut feel. Each acquisition takes six months to report on a consistent basis, and the bank asked for a 13-week cash forecast we could not produce in under two weeks.',
  fs_strategy_clarity: 3,
  fs_operating_model: 'Shared back office, local operations',
  fs_current_gl: 'QuickBooks Enterprise 2021 (Keystone HQ); Sage 100 v2020 (Delmarva and Lehigh)',
  fs_gl_years: 11,
  fs_other_systems: ['CRM', 'Payroll / HRIS', 'Inventory / warehouse', 'Banking / treasury', 'BI / reporting tool', 'E-commerce platform'],
  fs_integrations: 9,
  fs_spreadsheets: 23,
  fs_system_satisfaction: 2,
  fs_contract_end: 'Sage 100 v2020 support ends June 2027. QuickBooks Enterprise renews every January.',
  fs_it_support: 'Outsourced IT / MSP',
  fs_close_days: 15,
  fs_close_target: 6,
  fs_manual_jes: 340,
  fs_ap_volume: 4200,
  fs_ar_volume: 6800,
  fs_pain_close: 5,
  fs_pain_ap: 3,
  fs_pain_ar: 3,
  fs_pain_consol: 5,
  fs_pain_fpa: 4,
  fs_manual_worst: 'Intercompany and consolidation. Three controllers email trial balances, our senior accountant maps them to a master chart in Excel, eliminates intercompany sales and freight by hand, and books top-side entries. It takes four days and we find errors most months.',
  fs_report_gaps: 'Gross margin by customer and product line after freight and rebates; weekly cash; budget vs. actual by branch before the 20th; inventory turns by warehouse.',
  metrics_tracked: 'Revenue and gross margin by company, EBITDA vs. budget, DSO, inventory value, covenant ratios.',
  fs_data_quality: 2,
  fs_coa: 'Different in each entity',
  fs_history: '2–3 years of detail',
  fs_revrec: 'Simple: invoice = revenue',
  fs_entities: 4,
  fs_currencies: 1,
  fs_audit: 'Audited annually',
  fs_audit_findings: 'FY2025 management letter: inconsistent inventory cut-off across entities, manual journal entries posted without review, and late intercompany reconciliations. Two audit adjustments to inventory reserves.',
  fs_compliance: ['US GAAP', 'Multi-state sales tax', 'Lender covenant reporting'],
  fs_selection_stage: 'Talking to vendors',
  fs_vendors: 'NetSuite, Microsoft Dynamics 365 Business Central, Acumatica',
  fs_partner: 'Talking to partners',
  fs_criteria_rank: ['Scales with acquisitions', 'Fit with our processes', 'Reporting and analytics', 'Total cost over 5 years', 'Integration with our other systems', 'Ease of use', 'Speed to implement', 'Vendor and partner strength'],
  fs_requirements: 'A rough list',
  fs_finance_team: 14,
  fs_users: 140,
  fs_project_lead: '25–50%',
  fs_change_capacity: 2,
  fs_past_implementations: 'Our controller led a Sage rollout at her previous company. Our 2024 warehouse system rollout ran four months late because branch managers never had time for testing.',
  fs_key_person_risk: 'Tom Alvarez, senior accountant, built and runs the consolidation workbook. Only the Delmarva controller understands their rebate accruals.',
  budget: '$150K–$300K',
  fs_golive: 'January 1, 2028 — start of our fiscal year, so we do not convert mid-year.',
  timing: 'No go-live in Q4 (peak season for safety products). Audit fieldwork in March. Board meetings in February, May, August and November. Lender covenant reporting due by the 20th each month.',
  non_negotiables: 'We will not replace the warehouse management system in this project. No reduction in finance headcount as a result.',
  decision_maker: 'Maria Chen (CFO), with board approval for spend over $250K',
  fs_sponsor: 'Greg Walsh, CEO',
  stakeholders: 'Greg Walsh (CEO): wants the acquisition engine to run faster. Ray Booker (COO): owns warehouses, worried about disruption to shipping. Dev Patel (IT director): prefers Microsoft and owns integrations. Ellen Park (PE operating partner): wants board reporting by day 10.',
  politics: 'The Delmarva and Lehigh controllers worry a shared back office means their jobs move to HQ. Dev and Maria disagree on NetSuite vs. Dynamics.',
  kickoff_attendees: 'Maria, Greg, Ray, Dev, the three controllers',
  problem_1: 'Consolidating four entities in Excel makes close take 15 days',
  problem_1_sev: 5,
  problem_2: 'No margin visibility by customer or product line',
  problem_2_sev: 4,
  problem_3: 'Each acquisition takes six months to integrate into reporting',
  problem_3_sev: 4,
  tried: 'Bought a consolidation add-on in 2025; it needed a common chart of accounts we did not have, so we stopped using it. Started a NetSuite evaluation in 2024 that stalled when the previous CFO left.',
  why_failed: 'We tried to fix tools before agreeing on a common chart of accounts and how acquired companies would run. Nobody owned the project full time.',
  fs_biggest_fear: 'That we go live and cannot ship or invoice for two weeks, or that we spend $500K rebuilding our old processes in a new system.',
  file_coa: [], file_financials: [], file_systems: [], file_other: [],
};

export const FINSYS_SAMPLE_AI_REPLY = `\`\`\`json
{
 "deck": {
  "title": "Keystone: one finance platform for growth",
  "subtitle": "What we heard, what the system must enable, and the road to go-live",
  "health": "Yellow",
  "slides": [
   {"layout": "summary", "section": "Executive summary", "title": "Keystone's acquisition strategy has outgrown four separate ledgers and Excel",
    "items": [
     {"label": "Close", "value": "15 days", "answer": "Close is 2.5x the 6-day target, driven by manual consolidation", "tone": "bad"},
     {"label": "Entities", "value": "4", "answer": "Four entities on three ledgers, with two more acquisitions coming", "tone": "warn"},
     {"label": "Visibility", "value": "None", "answer": "No margin by customer or product line after freight and rebates", "tone": "bad"},
     {"label": "Budget", "value": "$150–300K", "answer": "Budget looks low for 4 entities and 140 users; confirm scope", "tone": "warn"},
     {"label": "Deadline", "value": "Jan 2028", "answer": "Fiscal-year go-live is achievable if selection ends by Q1", "tone": "neutral"},
     {"label": "First step", "value": "3 decisions", "answer": "Operating model, chart of accounts, then software", "tone": "neutral"}
    ],
    "takeaway": "Decide how the business will run before choosing the system that runs it.",
    "notes": "Open with the strategy, not the software: $165M to $300M, half through acquisitions. Every acquisition today adds a ledger and six months of reporting work. Confirm with Maria whether the $150–300K budget covers software only or software plus implementation; for four entities and 140 users, implementation alone is often in that range."},
   {"layout": "bignumbers", "section": "Current state", "title": "A 15-day close across four entities runs on 23 spreadsheets",
    "items": [
     {"icon": "calendar", "value": "15 days", "label": "To close the month", "sub": "Target: 6 days", "tone": "bad"},
     {"icon": "flag", "value": "4", "label": "Entities on three different ledgers", "sub": "QuickBooks + Sage 100 (support ends 2027)", "tone": "warn"},
     {"icon": "alert", "value": "23", "label": "Critical spreadsheets in close and reporting", "sub": "340 manual journal entries a month", "tone": "bad"}
    ],
    "takeaway": "The close is slow because the structure is fragmented, not because the team is slow.",
    "notes": "Sage 100 support ends June 2027, six months before the target go-live, so there is no slack. Ask who owns each of the 23 spreadsheets."},
   {"layout": "hero", "section": "Where it hurts", "title": "Close and consolidation are the most painful processes, both rated 5 of 5",
    "chart": "pain",
    "stats": [
     {"value": "5/5", "label": "Month-end close and consolidation", "tone": "bad"},
     {"value": "4 days", "label": "Spent on intercompany each month", "tone": "bad"},
     {"value": "3/5", "label": "AP and billing: improve, but not first", "tone": "warn"}
    ],
    "takeaway": "Requirements and demos should start with consolidation, not AP.",
    "notes": "The client ranks multi-entity consolidation first and faster close second. Vendor demos should be scripted around a four-entity close with intercompany eliminations and freight."},
   {"layout": "ranked", "section": "Key problems", "title": "Consolidation is the root problem; margin and M&A integration follow from it",
    "items": [
     {"title": "Excel consolidation makes close take 15 days", "detail": "Three controllers, four ledgers, top-side entries, errors most months", "score": "5", "tone": "bad"},
     {"title": "No margin by customer or product line", "detail": "Freight and rebates not allocated; reps discount blindly", "score": "4", "tone": "bad"},
     {"title": "Acquisitions take six months to integrate", "detail": "No common chart of accounts; two more deals in the pipeline", "score": "4", "tone": "bad"}
    ],
    "takeaway": "A common chart of accounts unlocks all three.",
    "notes": "Note the 2025 audit findings: inventory cut-off, unreviewed manual entries, late intercompany. These belong in requirements as controls, not just features."},
   {"layout": "cards", "section": "Strategy fit", "title": "The system must make acquisitions cheaper and margins visible",
    "cards": [
     {"title": "Fold in an acquisition in 90 days", "body": "Standard chart of accounts, entity template and data playbook so deal #3 and #4 report on day one.", "tone": "good"},
     {"title": "Margin by customer and product line", "body": "Allocate freight and rebates so pricing for the private-label line is based on real margin.", "tone": "good"},
     {"title": "13-week cash and covenants on time", "body": "Lender reporting by the 20th without a two-week Excel exercise.", "tone": "good"},
     {"title": "Ready for e-commerce and a future sale", "body": "Clean, audited, consolidated numbers support the PE exit thesis.", "tone": "good"}
    ],
    "takeaway": "Requirements come from the strategy first, today's pain second.",
    "notes": "This slide reframes the project from an accounting upgrade to an enabler of the PE value-creation plan. Ask Greg which of the four matters most to the board."},
   {"layout": "decisions", "section": "Focus areas", "title": "Three decisions come before choosing software",
    "items": [
     {"title": "Agree the operating model", "body": "Shared back office, local operations: define what centralizes and what stays local by week 4. Owner: Greg with BKCG.", "why": "Controllers fear their roles move to HQ"},
     {"title": "Design one chart of accounts", "body": "Common COA and entity structure before data moves; owner Maria with the controllers by week 8.", "why": "The 2025 consolidation add-on failed without it"},
     {"title": "Select on scripted demos", "body": "NetSuite, Business Central and Acumatica demo a four-entity close; decision by week 12.", "why": "CFO and IT director disagree on vendor"}
    ],
    "takeaway": "Settle the operating model first; it settles the vendor debate.",
    "notes": "Scripted demos with a weighted scorecard take the NetSuite-versus-Microsoft disagreement out of opinion. Include Dev in writing the integration scenarios."},
   {"layout": "compare", "section": "Today vs. future", "title": "From four ledgers and Excel to one consolidated platform",
    "rows": [
     {"icon": "calendar", "from": "15-day close", "to": "6-day close", "why": "Board reporting by day 10"},
     {"icon": "flag", "from": "Consolidation in Excel", "to": "Automated eliminations across entities", "why": "4 entities, more coming"},
     {"icon": "chart", "from": "Margin by company only", "to": "Margin by customer and product", "why": "Private-label pricing"},
     {"icon": "people", "from": "Acquisitions take 6 months", "to": "Acquisitions report in 90 days", "why": "Two deals in pipeline"}
    ],
    "takeaway": "Each target becomes a go-live success measure.",
    "notes": "Use these four rows as the success criteria in the project charter."},
   {"layout": "cards", "section": "Risks", "title": "Budget, people and timing could derail the project",
    "cards": [
     {"title": "Budget may not match scope", "body": "$150–300K for 4 entities and 140 users; confirm whether it includes implementation.", "tone": "bad"},
     {"title": "Team is already stretched", "body": "Change capacity rated 2/5; project lead available only 25–50%.", "tone": "warn"},
     {"title": "Knowledge in two heads", "body": "Consolidation workbook and Delmarva rebates live with two people.", "tone": "warn"},
     {"title": "Tight calendar", "body": "Sage support ends June 2027; no Q4 go-live; audit fieldwork in March.", "tone": "warn"}
    ],
    "takeaway": "Fix budget and a full-time project lead before signing a vendor.",
    "notes": "The 2024 warehouse rollout ran four months late because branch managers could not test; plan backfill for testers now."},
   {"layout": "timeline", "section": "Roadmap", "title": "Selection by week 12 keeps a January 2028 go-live on track",
    "items": [], "takeaway": "Steering committee approves the charter at kickoff.",
    "notes": "Timeline fills from the project plan. Critical path: operating model, chart of accounts, selection, design sign-off, data migration rehearsals."}
  ]
 },
 "plan": {"rows": [
  {"phase": "Strategy & requirements", "workstream": "Governance", "task": "Kickoff, charter and steering committee", "owner": "BKCG, Maria Chen", "start": 1, "weeks": 1, "deliverable": "Project charter", "milestone": true},
  {"phase": "Strategy & requirements", "workstream": "Strategy", "task": "Operating model for acquired companies", "owner": "BKCG, Greg Walsh", "start": 1, "weeks": 4, "deliverable": "Future-state operating model", "milestone": false},
  {"phase": "Strategy & requirements", "workstream": "Process design", "task": "Current-state close and consolidation maps", "owner": "BKCG, controllers", "start": 2, "weeks": 3, "deliverable": "Process maps", "milestone": false},
  {"phase": "Strategy & requirements", "workstream": "Chart of accounts & entities", "task": "Common chart of accounts design", "owner": "Maria Chen, controllers", "start": 3, "weeks": 5, "deliverable": "Draft common COA", "milestone": false},
  {"phase": "Strategy & requirements", "workstream": "Process design", "task": "Prioritized requirements and demo scripts", "owner": "BKCG, Dev Patel", "start": 4, "weeks": 3, "deliverable": "Requirements signed off", "milestone": true},
  {"phase": "Selection", "workstream": "Selection", "task": "Scripted demos: NetSuite, Business Central, Acumatica", "owner": "BKCG, selection team", "start": 7, "weeks": 3, "deliverable": "Demo scorecards", "milestone": false},
  {"phase": "Selection", "workstream": "Selection", "task": "Partner proposals and reference calls", "owner": "BKCG", "start": 8, "weeks": 3, "deliverable": "Partner comparison", "milestone": false},
  {"phase": "Selection", "workstream": "Governance", "task": "Budget confirmation and board approval", "owner": "Maria Chen", "start": 10, "weeks": 2, "deliverable": "Approved budget", "milestone": false},
  {"phase": "Selection", "workstream": "Governance", "task": "Vendor and partner selected", "owner": "Maria Chen, Greg Walsh", "start": 12, "weeks": 1, "deliverable": "Signed contracts", "milestone": true},
  {"phase": "Design", "workstream": "Chart of accounts & entities", "task": "Final COA, entities and intercompany rules", "owner": "Implementation partner, controllers", "start": 13, "weeks": 4, "deliverable": "COA and entity design", "milestone": false},
  {"phase": "Design", "workstream": "Reporting", "task": "Margin, cash and covenant reporting design", "owner": "BKCG, FP&A", "start": 14, "weeks": 4, "deliverable": "Report catalog", "milestone": false},
  {"phase": "Design", "workstream": "Integrations", "task": "WMS, CRM, bank and e-commerce integration design", "owner": "Dev Patel, implementation partner", "start": 14, "weeks": 4, "deliverable": "Integration specs", "milestone": false},
  {"phase": "Design", "workstream": "Governance", "task": "Design sign-off", "owner": "Maria Chen", "start": 18, "weeks": 1, "deliverable": "Signed-off design", "milestone": true},
  {"phase": "Build & data migration", "workstream": "Configuration", "task": "Configure ledgers, consolidation and approvals", "owner": "Implementation partner", "start": 19, "weeks": 8, "deliverable": "Configured system", "milestone": false},
  {"phase": "Build & data migration", "workstream": "Data migration", "task": "Data cleanup and mapping (2 years of detail)", "owner": "Controllers, BKCG", "start": 16, "weeks": 10, "deliverable": "Clean master data", "milestone": false},
  {"phase": "Build & data migration", "workstream": "Integrations", "task": "Build and test integrations", "owner": "Dev Patel, implementation partner", "start": 21, "weeks": 6, "deliverable": "Working integrations", "milestone": false},
  {"phase": "Build & data migration", "workstream": "Data migration", "task": "Two migration rehearsals", "owner": "Implementation partner", "start": 26, "weeks": 4, "deliverable": "Rehearsal sign-off", "milestone": true},
  {"phase": "Test & train", "workstream": "Testing", "task": "User acceptance testing with backfilled testers", "owner": "Controllers, branch managers", "start": 30, "weeks": 4, "deliverable": "UAT sign-off", "milestone": false},
  {"phase": "Test & train", "workstream": "Change & training", "task": "Role-based training for 140 users", "owner": "BKCG, implementation partner", "start": 32, "weeks": 3, "deliverable": "Trained users", "milestone": false},
  {"phase": "Test & train", "workstream": "Governance", "task": "Go / no-go decision", "owner": "Steering committee", "start": 35, "weeks": 1, "deliverable": "Go decision", "milestone": true},
  {"phase": "Go-live & hypercare", "workstream": "Cutover", "task": "Cutover and go-live (fiscal year start)", "owner": "Implementation partner, controllers", "start": 36, "weeks": 1, "deliverable": "Live system", "milestone": true},
  {"phase": "Go-live & hypercare", "workstream": "Cutover", "task": "Hypercare and first close on the new system", "owner": "All", "start": 37, "weeks": 5, "deliverable": "First 6-day close", "milestone": true}
 ]}
}
\`\`\``;
