// Realistic fake client for demos and testing. Nothing here is a real company.
export const SAMPLE_ANSWERS = {
  company_name: 'Harborline Health Software',
  respondent: 'Dana Ruiz, CEO and co-founder',
  one_liner: 'Scheduling and patient-messaging software for multi-location dental groups, priced per location.',
  stage: 'Growth ($1M–$10M)',
  revenue_range: '$5M–$10M',
  team_size: 48,
  business_model: ['SaaS subscription', 'Services / consulting'],
  why_now: 'Growth stalled around $6M ARR for three quarters. The board wants a credible 2027 plan at the March meeting, and the leadership team disagrees about whether the problem is product (no two-way texting) or sales (we lost our VP Sales in June).',
  success_90: 'Board approves a focused 2027 plan; we have picked one segment to lead with; pipeline coverage back above 3x; a decision on whether to raise a bridge.',
  goal_rank: ['Grow revenue', 'Fix go-to-market', 'Improve product-market fit', 'Raise capital', 'Improve profitability', 'Build the team / org', 'Prepare for an exit'],
  plan_confidence: 2,
  current_strategy: 'Win mid-size dental groups (5–40 locations) with a direct inside-sales team, then expand into billing and reminders add-ons. In 2025 we also started selling to single-location practices through a low-touch starter tier.',
  revenue_target: 8200000,
  revenue_forecast: 6700000,
  growth_rate: 9,
  results_detail: 'Better: retention held (GRR 91%) and the reminders add-on is in 38% of accounts. Worse: new bookings missed plan by about 30%. Two enterprise deals (DSOs with 120+ locations) slipped twice, outbound produced almost nothing, and the starter tier pulled reps into small deals.',
  ideal_customer: 'Dental groups with 10–30 locations, bought by the COO or Director of Operations after a bad quarter of front-desk turnover and missed appointments.',
  customer_count: 214,
  top_customer_share: 11,
  grr: 91,
  nrr: 98,
  competitors: 'Weave, NexHealth, Dentrix built-in scheduling, spreadsheets',
  win_loss: 'We win on multi-location reporting and implementation support. We lose on two-way texting (Weave) and on price against NexHealth for smaller groups.',
  market_position: 3,
  channels: ['Inbound / content', 'Outbound sales', 'Referrals', 'Events'],
  sales_motion: 'Inside sales',
  acv: 21000,
  sales_cycle: 74,
  win_rate: 27,
  cac: 26000,
  pricing: '$350 per location per month on annual contracts; unchanged since 2023. Average discount is 18% and reps discount at the end of every quarter.',
  rate_sales: 2,
  rate_marketing: 2,
  rate_pricing: 2,
  product_summary: 'Scheduling, reminders and multi-location reporting. Roadmap: two-way texting (Q1), online booking widget (Q2), insurance verification (2027).',
  rate_pmf: 3,
  product_gap: 'No two-way texting. Prospects ask for it in about half of demos.',
  leadership: 'Dana Ruiz CEO (6 yrs); Sam Patel CTO (6 yrs); VP Sales open since June; Priya Nair VP Customer Success (3 yrs); Kim Lee finance (contract, 2 days/week).',
  open_roles: 'VP Sales, product marketing manager',
  rate_org: 2,
  cash: 4100000,
  burn: 310000,
  runway: 18,
  gross_margin: 74,
  funding: 'Seed $3M (2021), Series A $9M (2023). Considering a $3M bridge in Q2 if bookings do not recover.',
  metrics_tracked: 'ARR, new bookings, churn, cash. We do not track pipeline coverage or CAC consistently.',
  problem_1: 'New bookings are about 30% below plan and pipeline is thin',
  problem_1_sev: 5,
  problem_2: 'Leadership disagrees on whether to fix product or sales first',
  problem_2_sev: 4,
  problem_3: 'Starter tier pulls reps into small, low-value deals',
  problem_3_sev: 3,
  tried: 'Hired an outbound agency for six months ($90K): 4 meetings, no deals. Launched the starter tier in 2025; it now takes 35% of rep time for 8% of new ARR.',
  why_failed: 'The agency never understood dental operations. The starter tier was priced to win, not to make money, and we never set rules for which deals reps should take.',
  budget: '$50K–$150K',
  timing: 'Board meeting March 12. If we raise a bridge, we need to start conversations by mid-April.',
  politics: 'Sam (CTO) believes the answer is two-way texting and is wary of pricing changes. Priya wants to slow new sales until onboarding is fixed.',
  non_negotiables: 'No layoffs in customer success. We will not exit the single-location market entirely this year.',
  decision_maker: 'Dana Ruiz, with board approval for budget over $250K',
  stakeholders: 'Sam Patel (CTO): owns roadmap. Priya Nair (VP CS): owns retention. Ellen Wu (board chair): pushing for profitability by 2027.',
  kickoff_attendees: 'Dana, Sam, Priya, Kim',
  board_involvement: 'Will review the plan',
  file_pitch: [], file_financials: [], file_board: [], file_other: [],
};

// A reply in the format the "Copy prompt" asks any AI to return, written for the sample client.
export const SAMPLE_AI_REPLY = `\`\`\`json
{
 "deck": {
  "title": "Harborline: fix pipeline before product bets",
  "subtitle": "What we heard and where we propose to focus first",
  "health": "Yellow",
  "slides": [
   {"layout": "summary", "section": "Executive summary", "title": "Harborline's growth problem is pipeline and focus, not retention",
    "items": [
     {"label": "Plan gap", "value": "-18%", "answer": "Revenue will land $1.5M below the $8.2M target", "tone": "bad"},
     {"label": "Runway", "value": "13 mo", "answer": "Cash ÷ burn says 13 months, not the 18 stated", "tone": "warn"},
     {"label": "Retention", "value": "91%", "answer": "Customers stay; the base is a strength to build on", "tone": "good"},
     {"label": "Top problem", "value": "5/5", "answer": "Bookings 30% below plan with thin pipeline", "tone": "bad"},
     {"label": "Unit economics", "value": "~20 mo", "answer": "CAC payback is long because deals are discounted", "tone": "warn"},
     {"label": "Proposal", "value": "3 areas", "answer": "Segment focus, pricing discipline, a rebuilt sales engine", "tone": "neutral"}
    ],
    "takeaway": "The base is healthy; the growth engine and the plan need resetting.",
    "notes": "Open with the headline: retention is not the issue. The gap to plan comes from new bookings. Flag that the runway the client stated (18 months) does not match cash divided by burn (about 13 months) and ask Kim to confirm the burn figure. Ask Dana whether the board has seen the revised forecast."},
   {"layout": "bignumbers", "section": "Current state", "title": "Revenue will miss plan by 18% and runway is shorter than stated",
    "items": [
     {"icon": "down", "value": "$6.7M", "label": "Revenue now expected this year", "sub": "vs. $8.2M target", "tone": "bad"},
     {"icon": "clock", "value": "13 mo", "label": "Runway at current burn", "sub": "$4.1M cash · $310K/mo burn", "tone": "warn"},
     {"icon": "people", "value": "91%", "label": "Gross revenue retention", "sub": "Net retention 98%", "tone": "good"}
    ],
    "takeaway": "Any plan has to pay back inside about a year of cash.",
    "notes": "The stated runway is 18 months; cash of $4.1M at $310K a month burn gives about 13. Either burn has fallen recently or the runway figure includes the bridge. Confirm at kickoff. Growth was 9% last year against a plan that implied about 30%."},
   {"layout": "hero", "section": "Self-assessment", "title": "Leadership rates sales, marketing and pricing as its weakest areas",
    "chart": "ratings",
    "stats": [
     {"value": "2/5", "label": "Sales, marketing, pricing and alignment", "tone": "bad"},
     {"value": "3/5", "label": "Product-market fit and market position", "tone": "warn"}
    ],
    "takeaway": "The team's own ratings point at go-to-market, not product.",
    "notes": "Four areas score 2 of 5. Note that the CTO argues the fix is product (two-way texting) while product-market fit is rated higher than every go-to-market area. Use this chart to open the product-versus-sales debate with data rather than opinions."},
   {"layout": "ranked", "section": "Key problems", "title": "Thin pipeline is the most severe problem; the other two make it worse",
    "items": [
     {"title": "New bookings 30% below plan, thin pipeline", "detail": "Outbound agency: 4 meetings in 6 months; no pipeline coverage metric", "score": "5", "tone": "bad"},
     {"title": "Leaders split on product vs. sales", "detail": "CTO backs texting; VP CS wants to slow sales; VP Sales seat open", "score": "4", "tone": "bad"},
     {"title": "Starter tier pulls reps into small deals", "detail": "35% of rep time for 8% of new ARR", "score": "3", "tone": "warn"}
    ],
    "takeaway": "Problem 2 blocks the fix for problem 1: alignment comes first.",
    "notes": "Ask the team whether they agree with this order. The starter tier is a symptom of having no rules for which deals to pursue. The leadership split is the reason nothing has been decided since June."},
   {"layout": "cards", "section": "Opportunities", "title": "Three opportunities can close most of the gap without new product",
    "cards": [
     {"title": "Stop discounting by default", "body": "Average discount is 18% and price is unchanged since 2023. Halving discounting is worth roughly $0.4M a year.", "tone": "good"},
     {"title": "Focus reps on 10–30 location groups", "body": "Best customers are clearly defined; win rate is 27% when reps get qualified at-bats.", "tone": "good"},
     {"title": "Expand the base", "body": "GRR 91% but NRR only 98%: reminders is in 38% of accounts, billing add-on in few.", "tone": "good"}
    ],
    "takeaway": "Pricing discipline and focus are faster than the texting roadmap.",
    "notes": "The discount figure is the client's own. The $0.4M estimate assumes about $5M of new and renewing contract value repriced over a year at 9 points less discount; treat as directional. Expansion: ask Priya for add-on penetration by account size."},
   {"layout": "decisions", "section": "Focus areas", "title": "We propose three focus areas for the first 90 days",
    "items": [
     {"title": "Pick the lead segment", "body": "Agree the 10–30 location focus and deal rules by week 6; owner Dana with BKCG.", "why": "Starter tier: 35% of rep time, 8% of ARR"},
     {"title": "Reset pricing and discount rules", "body": "Test a packaging and discount policy on new deals from week 8; owner Kim with BKCG.", "why": "18% average discount, price unchanged since 2023"},
     {"title": "Rebuild the sales engine", "body": "Define pipeline coverage, hire the VP Sales, replace the agency with a focused outbound play by week 12.", "why": "Bookings 30% below plan"}
    ],
    "takeaway": "One segment, one price policy, one pipeline metric.",
    "notes": "Two-way texting stays on the roadmap; this plan does not depend on it. That framing should help with Sam. The VP Sales hire is the long pole; start the search in week 1."},
   {"layout": "compare", "section": "Today vs. proposed", "title": "The proposal narrows the focus and adds discipline",
    "fromLabel": "Today", "toLabel": "Proposed",
    "rows": [
     {"icon": "target", "from": "Sell to every practice size", "to": "Lead with 10–30 location groups", "why": "Best-fit customers convert and stay"},
     {"icon": "cash", "from": "18% average discount, no rules", "to": "Discount approval above 10%", "why": "Price unchanged since 2023"},
     {"icon": "chart", "from": "ARR and bookings only", "to": "Weekly pipeline coverage target 3x", "why": "Gap was visible too late"},
     {"icon": "people", "from": "VP Sales seat open since June", "to": "Hire by week 12", "why": "No owner for the number"}
    ],
    "takeaway": "Each change is reversible and measurable within a quarter.",
    "notes": "Walk through each row and ask who owns it on the client side."},
   {"layout": "cards", "section": "Risks", "title": "Cash and alignment are the risks that could derail the plan",
    "cards": [
     {"title": "Runway may be 13 months, not 18", "body": "If correct, the bridge decision moves up to April.", "tone": "bad"},
     {"title": "CTO and VP CS not bought in", "body": "Both favor different fixes; involve them in the diagnosis, not the readout.", "tone": "warn"},
     {"title": "Board timing", "body": "March 12 board meeting leaves 10 weeks to land a plan.", "tone": "warn"},
     {"title": "Pricing change spooks customers", "body": "Apply new rules to new deals first; renewals later.", "tone": "warn"}
    ],
    "takeaway": "Confirm burn and get Sam and Priya into the diagnostic early.",
    "notes": "The runway discrepancy is the most urgent item to confirm at kickoff."},
   {"layout": "timeline", "section": "Next steps", "title": "Twelve weeks to an approved plan, with a decision at week 8",
    "items": [], "takeaway": "Readout in week 5 and board-ready plan before March 12.",
    "notes": "Timeline fills from the project plan. Key dates: diagnostic readout week 5, strategy workshop week 8, approval week 12."}
  ]
 },
 "plan": {"rows": [
  {"phase": "Discover", "workstream": "Engagement", "task": "Kickoff and goals alignment", "owner": "BKCG, Dana Ruiz", "start": 1, "weeks": 1, "deliverable": "Agreed goals and scope", "milestone": true},
  {"phase": "Discover", "workstream": "Engagement", "task": "Leadership interviews (Dana, Sam, Priya, Kim)", "owner": "BKCG", "start": 1, "weeks": 2, "deliverable": "Interview synthesis", "milestone": false},
  {"phase": "Discover", "workstream": "Finance", "task": "Confirm burn, runway and bridge timing", "owner": "Kim Lee", "start": 1, "weeks": 2, "deliverable": "Cash model", "milestone": false},
  {"phase": "Discover", "workstream": "Sales", "task": "Pipeline and lost-deal data pull", "owner": "Dana Ruiz", "start": 1, "weeks": 2, "deliverable": "Pipeline data pack", "milestone": false},
  {"phase": "Discover", "workstream": "Customers", "task": "Customer and lost-deal interviews (10)", "owner": "BKCG", "start": 2, "weeks": 3, "deliverable": "Customer insights", "milestone": false},
  {"phase": "Diagnose", "workstream": "Segment", "task": "Segment profitability and win-rate analysis", "owner": "BKCG", "start": 3, "weeks": 2, "deliverable": "Segment scorecard", "milestone": false},
  {"phase": "Diagnose", "workstream": "Pricing", "task": "Discount and price-realization analysis", "owner": "BKCG, Kim Lee", "start": 3, "weeks": 2, "deliverable": "Pricing diagnostic", "milestone": false},
  {"phase": "Diagnose", "workstream": "Sales", "task": "Sales funnel and capacity diagnostic", "owner": "BKCG", "start": 3, "weeks": 2, "deliverable": "Funnel diagnostic", "milestone": false},
  {"phase": "Diagnose", "workstream": "Engagement", "task": "Diagnostic readout to leadership", "owner": "BKCG", "start": 5, "weeks": 1, "deliverable": "Readout deck", "milestone": true},
  {"phase": "Design", "workstream": "Segment", "task": "Lead segment and deal rules", "owner": "Dana Ruiz, BKCG", "start": 6, "weeks": 2, "deliverable": "Segment strategy", "milestone": false},
  {"phase": "Design", "workstream": "Pricing", "task": "Packaging and discount policy", "owner": "Kim Lee, BKCG", "start": 6, "weeks": 2, "deliverable": "Pricing policy", "milestone": false},
  {"phase": "Design", "workstream": "Sales", "task": "Pipeline coverage model and outbound play", "owner": "BKCG", "start": 6, "weeks": 3, "deliverable": "Sales playbook v1", "milestone": false},
  {"phase": "Hiring", "workstream": "Sales", "task": "VP Sales search and scorecard", "owner": "Dana Ruiz", "start": 2, "weeks": 10, "deliverable": "VP Sales hired", "milestone": false},
  {"phase": "Design", "workstream": "Engagement", "task": "Leadership strategy workshop", "owner": "BKCG, leadership team", "start": 8, "weeks": 1, "deliverable": "Chosen direction", "milestone": true},
  {"phase": "Plan & mobilize", "workstream": "Execution", "task": "90-day action plan with owners", "owner": "BKCG, leadership team", "start": 9, "weeks": 2, "deliverable": "90-day plan", "milestone": false},
  {"phase": "Plan & mobilize", "workstream": "Execution", "task": "KPI scorecard and weekly cadence", "owner": "Kim Lee", "start": 9, "weeks": 2, "deliverable": "Weekly scorecard", "milestone": false},
  {"phase": "Plan & mobilize", "workstream": "Finance", "task": "Board pack and bridge decision", "owner": "Dana Ruiz, Kim Lee", "start": 10, "weeks": 2, "deliverable": "Board-ready plan", "milestone": false},
  {"phase": "Plan & mobilize", "workstream": "Engagement", "task": "Final recommendation and approval", "owner": "Dana Ruiz", "start": 12, "weeks": 1, "deliverable": "Approved plan", "milestone": true}
 ]}
}
\`\`\``;
